######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 25 17:10:26 2010
######################################################################

TEMPLATE = app
TARGET = mainwindow
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
CONFIG += qt debug
