######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 24 05:27:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ftpssl.h mainwindow.h
FORMS += main.ui
SOURCES += main.cpp mainwindow.cpp
QT += network
